#!/bin/bash
set -e

# ============================================
# FreeLink v3.12.0-aurora — Install Script
# Multi-server VPN panel with Hysteria 2
# ============================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

print_banner() {
    echo -e "${CYAN}"
    echo "  ╔══════════════════════════════════════╗"
    echo "  ║       FreeLink VPN Panel Setup       ║"
    echo "  ║          v3.12.0-aurora              ║"
    echo "  ╚══════════════════════════════════════╝"
    echo -e "${NC}"
}

print_step() {
    echo -e "\n${GREEN}[$1/16]${NC} $2"
}

print_ok() {
    echo -e "  ${GREEN}✓${NC} $1"
}

print_err() {
    echo -e "  ${RED}✗${NC} $1"
}

# ============================================
# 1. Check root
# ============================================
print_step "1" "Checking root..."
if [ "$(id -u)" -ne 0 ]; then
    print_err "Run as root: sudo ./install.sh"
    exit 1
fi
print_ok "Running as root"

# ============================================
# 2. Select language
# ============================================
print_step "2" "Language / Язык"
echo "  1) English"
echo "  2) Русский"
read -p "  Choice [2]: " LANG_CHOICE
LANG_CHOICE=${LANG_CHOICE:-2}
if [ "$LANG_CHOICE" = "1" ]; then
    LANG_CODE="en"
else
    LANG_CODE="ru"
fi
print_ok "Language: $LANG_CODE"

# ============================================
# 3. Collect configuration
# ============================================
print_step "3" "Configuration"
echo -e "  ${YELLOW}Enter your server details:${NC}"
read -p "  Domain (e.g. vpn.example.com): " DOMAIN
read -p "  Server IP: " SERVER_IP
read -p "  Telegram Bot Token: " TG_TOKEN
read -p "  Telegram Admin ID: " TG_ADMIN
read -p "  Panel port [8000]: " PANEL_PORT
PANEL_PORT=${PANEL_PORT:-8000}

# Validate inputs
if [ -z "$DOMAIN" ] || [ -z "$SERVER_IP" ] || [ -z "$TG_TOKEN" ] || [ -z "$TG_ADMIN" ]; then
    print_err "All fields are required!"
    exit 1
fi
print_ok "Configuration collected"

# ============================================
# 4. Install OS packages
# ============================================
print_step "4" "Installing system packages..."
apt-get update -qq
apt-get install -y -qq python3 python3-pip python3-venv python3-dev \
    nginx certbot python3-certbot-nginx \
    postgresql postgresql-client \
    curl git openssl ufw > /dev/null 2>&1
print_ok "System packages installed"

# ============================================
# 5. Clone project
# ============================================
print_step "5" "Downloading FreeLink..."
if [ -d "/opt/freelink" ]; then
    echo -e "  ${YELLOW}/opt/freelink exists, updating...${NC}"
    cd /opt/freelink
    git pull -q 2>/dev/null || true
else
    git clone https://github.com/R3G1ST/FreeLink.git /opt/freelink -q
    cd /opt/freelink
fi
print_ok "Project downloaded to /opt/freelink"

# ============================================
# 6. Setup PostgreSQL
# ============================================
print_step "6" "Setting up PostgreSQL..."

# Generate random password for PostgreSQL
PG_PASS=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)

# Create user and database
sudo -u postgres psql -c "CREATE USER freelink WITH PASSWORD '${PG_PASS}';" 2>/dev/null || true
sudo -u postgres psql -c "CREATE DATABASE freelink_db OWNER freelink ENCODING 'UTF8';" 2>/dev/null || true
sudo -u postgres psql -c "ALTER USER freelink WITH PASSWORD '${PG_PASS}';" 2>/dev/null

# Ensure PostgreSQL accepts local connections
PG_HBA="/etc/postgresql/16/main/pg_hba.conf"
if [ ! -f "$PG_HBA" ]; then
    PG_HBA=$(find /etc/postgresql -name pg_hba.conf 2>/dev/null | head -1)
fi
if [ -f "$PG_HBA" ]; then
    # Add scram-sha-256 auth for localhost if not present
    if ! grep -q "host.*freelink_db.*127.0.0.1" "$PG_HBA" 2>/dev/null; then
        echo "host freelink_db freelink 127.0.0.1/32 scram-sha-256" >> "$PG_HBA"
        systemctl restart postgresql 2>/dev/null || true
    fi
fi
print_ok "PostgreSQL configured (db: freelink_db, user: freelink)"

# ============================================
# 7. Create .env file
# ============================================
print_step "7" "Creating environment configuration..."

# Generate secrets
API_TOKEN=$(openssl rand -hex 32)
NODE_API_KEY=$(openssl rand -hex 32)
OBFS_PASSWORD=$(openssl rand -hex 16)
HYSTERIA_USER_PASS=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 24)

# Generate SSH encryption key
cd /opt/freelink
source venv/bin/activate 2>/dev/null || true
python3 -m venv venv 2>/dev/null || true
source venv/bin/activate
pip install cryptography -q 2>/dev/null
SSH_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
deactivate 2>/dev/null || true

cat > /opt/freelink/.env << EOF
# FreeLink Environment Configuration
# Generated by install.sh on $(date)

# Telegram Bot Configuration
TELEGRAM_TOKEN=${TG_TOKEN}
TELEGRAM_ADMIN_IDS=${TG_ADMIN}

# Hysteria 2 Configuration
HYSTERIA_USER_PASSWORD=${HYSTERIA_USER_PASS}
HYSTERIA_OBFS_PASSWORD=${OBFS_PASSWORD}

# PostgreSQL Database
PG_HOST=127.0.0.1
PG_PORT=5432
PG_DB=freelink_db
PG_USER=freelink
PG_PASS=${PG_PASS}

# API Security
API_TOKEN=${API_TOKEN}

# Server Configuration
SERVER_IP=${SERVER_IP}
DOMAIN=${DOMAIN}

# CORS
ALLOWED_ORIGINS=https://${DOMAIN}

# SSH Encryption Key
SSH_ENCRYPTION_KEY=${SSH_KEY}

# Node API Key
NODE_API_KEY=${NODE_API_KEY}
EOF

chmod 600 /opt/freelink/.env
print_ok ".env created with all secrets"

# ============================================
# 8. Python environment
# ============================================
print_step "8" "Setting up Python environment..."
cd /opt/freelink
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt -q
deactivate
print_ok "Python dependencies installed"

# ============================================
# 9. Install Hysteria 2
# ============================================
print_step "9" "Installing Hysteria 2..."
if ! command -v hysteria &> /dev/null; then
    HYSTERIA_VERSION="2.9.3"
    curl -fsSL "https://github.com/apernet/hysteria/releases/download/app%2Fv${HYSTERIA_VERSION}/hysteria-linux-amd64" \
        -o /usr/local/bin/hysteria 2>/dev/null || {
        print_err "Failed to download Hysteria. Install manually:"
        echo "  https://github.com/apernet/hysteria/releases"
    }
    chmod +x /usr/local/bin/hysteria
fi
print_ok "Hysteria 2 installed"

# Create Hysteria config
mkdir -p /etc/hysteria/certs
cat > /etc/hysteria/config.yaml << EOF
listen: :443

tls:
  cert: /etc/letsencrypt/live/${DOMAIN}/fullchain.pem
  key: /etc/letsencrypt/live/${DOMAIN}/privkey.pem

auth:
  type: http
  http:
    url: "http://127.0.0.1:8001/auth"

obfs:
  type: salamander
  salamander:
    password: "${OBFS_PASSWORD}"

trafficStats:
  listen: 127.0.0.1:9999

quic:
  disablePathMTUDiscovery: true

masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com
    rewriteHost: true
EOF

# Hysteria systemd service
cat > /etc/systemd/system/hysteria-server.service << EOF
[Unit]
Description=Hysteria 2 Server
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/hysteria server -c /etc/hysteria/config.yaml
Restart=always
RestartSec=5
LimitNOFILE=infinity

[Install]
WantedBy=multi-user.target
EOF
print_ok "Hysteria configured"

# ============================================
# 10. SSL Certificate
# ============================================
print_step "10" "Setting up SSL certificate..."
if [ ! -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then
    certbot certonly --nginx -d "${DOMAIN}" --non-interactive --agree-tos \
        --email "admin@${DOMAIN}" 2>/dev/null || {
        echo -e "  ${YELLOW}Certbot failed, generating self-signed cert...${NC}"
        openssl req -x509 -nodes -newkey ec:<(openssl ecparam -name prime256v1) \
            -keyout /etc/hysteria/certs/key.pem \
            -out /etc/hysteria/certs/cert.pem \
            -subj "/CN=${DOMAIN}" -days 3650 2>/dev/null
        # Update Hysteria config to use self-signed
        sed -i "s|/etc/letsencrypt/live/${DOMAIN}/fullchain.pem|/etc/hysteria/certs/cert.pem|" /etc/hysteria/config.yaml
        sed -i "s|/etc/letsencrypt/live/${DOMAIN}/privkey.pem|/etc/hysteria/certs/key.pem|" /etc/hysteria/config.yaml
    }
fi
print_ok "SSL certificate ready"

# ============================================
# 11. Configure Nginx
# ============================================
print_step "11" "Configuring Nginx..."

# Determine SSL cert path
if [ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]; then
    SSL_CERT="/etc/letsencrypt/live/${DOMAIN}/fullchain.pem"
    SSL_KEY="/etc/letsencrypt/live/${DOMAIN}/privkey.pem"
else
    SSL_CERT="/etc/hysteria/certs/cert.pem"
    SSL_KEY="/etc/hysteria/certs/key.pem"
fi

cat > /etc/nginx/sites-available/freelink << EOF
server {
    listen 80;
    server_name ${DOMAIN};
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate ${SSL_CERT};
    ssl_certificate_key ${SSL_KEY};

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    charset utf-8;

    add_header Cache-Control "no-cache, no-store, must-revalidate, max-age=0" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        proxy_pass http://127.0.0.1:${PANEL_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_cache off;
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        proxy_read_timeout 360s;
        proxy_connect_timeout 30s;
        proxy_send_timeout 360s;
    }

    location /web/ {
        alias /opt/freelink/web/;
        charset utf-8;
        default_type text/html;
    }
}
EOF

ln -sf /etc/nginx/sites-available/freelink /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx 2>/dev/null || systemctl start nginx
print_ok "Nginx configured"

# ============================================
# 12. Create systemd services
# ============================================
print_step "12" "Creating systemd services..."

SERVICES=("api" "auth" "bot" "online" "traffic" "history" "monitor")
DESCRIPTIONS=("API Server" "Auth Server" "Telegram Bot" "Online Detector" "Traffic Saver" "Traffic History" "Resource Monitor")
SCRIPTS=("api.py" "auth.py" "bot.py" "online_detector.py" "save_traffic.py" "traffic_history.py" "resource_monitor.py")
INTERVALS=(5 5 5 5 10 30 10)

for i in "${!SERVICES[@]}"; do
    SVC=${SERVICES[$i]}
    DESC=${DESCRIPTIONS[$i]}
    SCRIPT=${SCRIPTS[$i]}
    SEC=${INTERVALS[$i]}

    cat > /etc/systemd/system/freelink-${SVC}.service << EOF
[Unit]
Description=FreeLink ${DESC}
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/freelink
EnvironmentFile=/opt/freelink/.env
ExecStart=/opt/freelink/venv/bin/python3 ${SCRIPT}
Restart=always
RestartSec=${SEC}

[Install]
WantedBy=multi-user.target
EOF
done
print_ok "7 systemd services created"

# ============================================
# 13. Configure firewall
# ============================================
print_step "13" "Configuring firewall..."
ufw --force enable 2>/dev/null || true
ufw allow 22/tcp 2>/dev/null || true
ufw allow 443/tcp 2>/dev/null || true
ufw allow 443/udp 2>/dev/null || true
ufw allow ${PANEL_PORT}/tcp 2>/dev/null || true
print_ok "Firewall configured (22, 443/tcp+udp)"

# ============================================
# 14. Setup cron jobs
# ============================================
print_step "14" "Setting up scheduled tasks..."
chmod +x /opt/freelink/scripts/backup.sh 2>/dev/null || true
chmod +x /opt/freelink/scripts/monitor.sh 2>/dev/null || true

# Add cron jobs (avoid duplicates)
(crontab -l 2>/dev/null | grep -v "freelink" ; \
 echo "0 3 * * * /opt/freelink/scripts/backup.sh >> /opt/freelink/logs/backup.log 2>&1" ; \
 echo "* * * * * /opt/freelink/scripts/monitor.sh >> /opt/freelink/logs/monitor.log 2>&1" \
) | crontab -

mkdir -p /opt/freelink/logs
print_ok "Cron jobs configured"

# ============================================
# 15. Start all services
# ============================================
print_step "15" "Starting services..."
systemctl daemon-reload

# Start PostgreSQL
systemctl enable postgresql 2>/dev/null || true
systemctl start postgresql 2>/dev/null || true

# Start Nginx
systemctl enable nginx 2>/dev/null || true
systemctl start nginx 2>/dev/null || true

# Start Hysteria
systemctl enable hysteria-server 2>/dev/null || true
systemctl start hysteria-server 2>/dev/null || true

# Start FreeLink services
for SVC in "${SERVICES[@]}"; do
    systemctl enable freelink-${SVC} 2>/dev/null || true
    systemctl start freelink-${SVC} 2>/dev/null || true
done
print_ok "All services started"

# ============================================
# 16. Create default admin
# ============================================
print_step "16" "Creating default admin..."
sleep 3  # Wait for API to start

# Create admin via API or directly in DB
ADMIN_PASS=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | head -c 12)
source venv/bin/activate
python3 -c "
import sys; sys.path.insert(0, '/opt/freelink')
import db
db.init_db()
import bcrypt
pw_hash = bcrypt.hashpw(b'${ADMIN_PASS}', bcrypt.gensalt(rounds=12)).decode()
db.save_admin('admin', {'password_hash': pw_hash, 'role': 'admin', 'created': '$(date -Iseconds)'})
print('Admin created: admin/${ADMIN_PASS}')
" 2>/dev/null || echo "  Create admin manually after first login"
deactivate 2>/dev/null || true
print_ok "Default admin ready"

# ============================================
# Done!
# ============================================
echo ""
echo -e "${CYAN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║        Installation Complete!                ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Panel URL:    ${GREEN}https://${DOMAIN}${NC}"
echo -e "  Admin login:  ${GREEN}admin${NC}"
echo -e "  Admin pass:   ${GREEN}${ADMIN_PASS}${NC}"
echo ""
echo -e "  ${YELLOW}⚠ Change admin password after first login!${NC}"
echo ""
echo -e "  Services:"
for SVC in "${SERVICES[@]}"; do
    if systemctl is-active freelink-${SVC} >/dev/null 2>&1; then
        echo -e "    ${GREEN}✓${NC} freelink-${SVC}"
    else
        echo -e "    ${RED}✗${NC} freelink-${SVC}"
    fi
done
if systemctl is-active hysteria-server >/dev/null 2>&1; then
    echo -e "    ${GREEN}✓${NC} hysteria-server"
else
    echo -e "    ${RED}✗${NC} hysteria-server"
fi
echo ""
